# Hypridle configuration

listener {
    timeout = 180
    on-timeout = hyprlock --grace 5
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
